<?php
/*
+------------------------------------------------
|   BitsB PHP based BitTorrent Tracker
|   =============================================
|   by d6bmg
|   Copyright (C) 2010-2011 BitsB v1.0
|   =============================================
|   svn: http:// coming soon.. :)
|   Licence Info: GPL
+------------------------------------------------
*/

$mood = array(
array('id'=> '1', 'name'=> '', 'image'=> 'Aggressive.gif'),
array('id'=> '2', 'name'=> '', 'image'=> 'Alienated.gif'),
array('id'=> '3', 'name'=> '', 'image'=> 'Amazed.gif'),
array('id'=> '4', 'name'=> '', 'image'=> 'Amused.gif'),
array('id'=> '5', 'name'=> '', 'image'=> 'Angelic.gif'),
array('id'=> '6', 'name'=> '', 'image'=> 'Angry.gif'),
array('id'=> '7', 'name'=> '', 'image'=> 'Apelike.gif'),
array('id'=> '8', 'name'=> '', 'image'=> 'Artistic.gif'),
array('id'=> '9', 'name'=> '', 'image'=> 'Asleep.gif'),
array('id'=> '10', 'name'=> '', 'image'=> 'Balanced.gif'),
array('id'=> '11', 'name'=> '', 'image'=> 'Banhappy.gif'),
array('id'=> '12', 'name'=> '', 'image'=> 'Bashful.gif'),
array('id'=> '13', 'name'=> '', 'image'=> 'Bitching.gif'),
array('id'=> '14', 'name'=> '', 'image'=> 'Blah.gif'),
array('id'=> '15', 'name'=> '', 'image'=> 'Bookworm.gif'),
array('id'=> '16', 'name'=> '', 'image'=> 'Bored.gif'),
array('id'=> '17', 'name'=> '', 'image'=> 'Breezy.gif'),
array('id'=> '18', 'name'=> '', 'image'=> 'Brooding.gif'),
array('id'=> '19', 'name'=> '', 'image'=> 'Busy.gif'),
array('id'=> '20', 'name'=> '', 'image'=> 'Buzzed.gif'),
array('id'=> '21', 'name'=> '', 'image'=> 'Chatty.gif'),
array('id'=> '22', 'name'=> '', 'image'=> 'Cheeky.gif'),
array('id'=> '23', 'name'=> '', 'image'=> 'Cheerful.gif'),
array('id'=> '24', 'name'=> '', 'image'=> 'Cloud_9.gif'),
array('id'=> '25', 'name'=> '', 'image'=> 'Cold.gif'),
array('id'=> '26', 'name'=> '', 'image'=> 'Coldturkey.gif'),
array('id'=> '27', 'name'=> '', 'image'=> 'Confused.gif'),
array('id'=> '28', 'name'=> '', 'image'=> 'Cool.gif'),
array('id'=> '29', 'name'=> '', 'image'=> 'Crappy.gif'),
array('id'=> '30', 'name'=> '', 'image'=> 'Creative.gif'),
array('id'=> '31', 'name'=> '', 'image'=> 'Curious.gif'),
array('id'=> '32', 'name'=> '', 'image'=> 'Cynical.gif'),
array('id'=> '33', 'name'=> '', 'image'=> 'Daring.gif'),
array('id'=> '34', 'name'=> '', 'image'=> 'Dead.gif'),
array('id'=> '35', 'name'=> '', 'image'=> 'Depressed.gif'),
array('id'=> '36', 'name'=> '', 'image'=> 'Devilish.gif'),
array('id'=> '37', 'name'=> '', 'image'=> 'Disagree.gif'),
array('id'=> '38', 'name'=> '', 'image'=> 'Doh.gif'),
array('id'=> '39', 'name'=> '', 'image'=> 'Doubtful.gif'),
array('id'=> '40', 'name'=> '', 'image'=> 'Dramaqueen.gif'),
array('id'=> '41', 'name'=> '', 'image'=> 'Dreaming.gif'),
array('id'=> '42', 'name'=> '', 'image'=> 'Drunk.gif'),
array('id'=> '43', 'name'=> '', 'image'=> 'Elated.gif'),
array('id'=> '44', 'name'=> '', 'image'=> 'Energetic.gif'),
array('id'=> '45', 'name'=> '', 'image'=> 'Fiendish.gif'),
array('id'=> '46', 'name'=> '', 'image'=> 'Fine.gif'),
array('id'=> '47', 'name'=> '', 'image'=> 'Flirty.gif'),
array('id'=> '48', 'name'=> '', 'image'=> 'Gloomy.gif'),
array('id'=> '49', 'name'=> '', 'image'=> 'Goofy.gif'),
array('id'=> '50', 'name'=> '', 'image'=> 'Grumpy.gif'),
array('id'=> '51', 'name'=> '', 'image'=> 'Happy.gif'),
array('id'=> '52', 'name'=> '', 'image'=> 'Horny.gif'),
array('id'=> '53', 'name'=> '', 'image'=> 'Hot.gif'),
array('id'=> '54', 'name'=> '', 'image'=> 'Hungover.gif'),
array('id'=> '55', 'name'=> '', 'image'=> 'In-Love.gif'),
array('id'=> '56', 'name'=> '', 'image'=> 'Innocent.gif'),
array('id'=> '57', 'name'=> '', 'image'=> 'Inpain.gif'),
array('id'=> '58', 'name'=> '', 'image'=> 'Insomnious.gif'),
array('id'=> '59', 'name'=> '', 'image'=> 'Inspired.gif'),
array('id'=> '60', 'name'=> '', 'image'=> 'Lonely.gif'),
array('id'=> '61', 'name'=> '', 'image'=> 'Lucky.gif'),
array('id'=> '62', 'name'=> '', 'image'=> 'Lurking.gif'),
array('id'=> '63', 'name'=> '', 'image'=> 'Mellow.gif'),
array('id'=> '64', 'name'=> '', 'image'=> 'Mischievious.gif'),
array('id'=> '65', 'name'=> '', 'image'=> 'Mondayblues.gif'),
array('id'=> '66', 'name'=> '', 'image'=> 'Musical.gif'),
array('id'=> '67', 'name'=> '', 'image'=> 'Nerdy.gif'),
array('id'=> '68', 'name'=> '', 'image'=> 'Notamused.gif'),
array('id'=> '69', 'name'=> '', 'image'=> 'Notworthy.gif'),
array('id'=> '70', 'name'=> '', 'image'=> 'Paranoid.gif'),
array('id'=> '71', 'name'=> '', 'image'=> 'Pensive.gif'),
array('id'=> '72', 'name'=> '', 'image'=> 'Predatory.gif'),
array('id'=> '73', 'name'=> '', 'image'=> 'Procrastinating.gif'),
array('id'=> '74', 'name'=> '', 'image'=> 'Psychedelic.gif'),
array('id'=> '75', 'name'=> '', 'image'=> 'Question.gif'),
array('id'=> '76', 'name'=> '', 'image'=> 'Relaxed.gif'),
array('id'=> '77', 'name'=> '', 'image'=> 'Roflmao.gif'),
array('id'=> '78', 'name'=> '', 'image'=> 'Sad.gif'),
array('id'=> '79', 'name'=> '', 'image'=> 'Scared.gif'),
array('id'=> '80', 'name'=> '', 'image'=> 'Scurvy.gif'),
array('id'=> '81', 'name'=> '', 'image'=> 'Shocked.gif'),
array('id'=> '82', 'name'=> '', 'image'=> 'Sick.gif'),
array('id'=> '83', 'name'=> '', 'image'=> 'Sleepy.gif'),
array('id'=> '84', 'name'=> '', 'image'=> 'Sluggish.gif'),
array('id'=> '85', 'name'=> '', 'image'=> 'Sneaky.gif'),
array('id'=> '86', 'name'=> '', 'image'=> 'Snobbish.gif'),
array('id'=> '87', 'name'=> '', 'image'=> 'Spaced.gif'),
array('id'=> '88', 'name'=> '', 'image'=> 'Spooky.gif'),
array('id'=> '89', 'name'=> '', 'image'=> 'Sporty.gif'),
array('id'=> '90', 'name'=> '', 'image'=> 'Starving.gif'),
array('id'=> '91', 'name'=> '', 'image'=> 'Stressed.gif'),
array('id'=> '92', 'name'=> '', 'image'=> 'Sunshine.gif'),
array('id'=> '93', 'name'=> '', 'image'=> 'Sweettooth.gif'),
array('id'=> '94', 'name'=> '', 'image'=> 'Thinking.gif'),
array('id'=> '95', 'name'=> '', 'image'=> 'Tired.gif'),
array('id'=> '96', 'name'=> '', 'image'=> 'Torn.gif'),
array('id'=> '97', 'name'=> '', 'image'=> 'Twisted.gif'),
array('id'=> '98', 'name'=> '', 'image'=> 'Veggedout.gif'),
array('id'=> '99', 'name'=> '', 'image'=> 'Volatile.gif'),
array('id'=> '100', 'name'=> '', 'image'=> 'Woot.gif'),
array('id'=> '101', 'name'=> '', 'image'=> 'Worried.gif'),
array('id'=> '102', 'name'=> '', 'image'=> 'Yeehaw.gif'),
);
?>